security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            memory: null

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/v1/api
            stateless: true
            custom_authenticator: App\Security\TokenAuthenticator

    access_control:
        - { path: ^/v1/api/users, roles: ROLE_USER }
